services:
  libretranslate:
    image: libretranslate/libretranslate
    ports:
      - "5000:5000"
    environment:
      - LT_LOAD_ONLY=en,ja
    volumes:
      - ./data:/home/libretranslate/.local/share/argos-translate