//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameTranslationOverlay.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameTranslationOverlay.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAA5R+/frGFYUuoGX9oI3+FLgAAAAACAAAAAAAQZgAAAAEAACAAAAAy69EmpIuRO4y6QaHwhg7oK3RZ/sCfD+6nDna0q7fTogAAAAAOgAAAAAIAACAAAAD/CONRi9Af3mSz1bUPWpK7r15KmrchjMmsZKFd5RaMETAAAAAzFlF4fOggudJPgxQKPo+s+nRn1/gLnl2kLLLRzJsKJEsBXTXAdR5ZNLCb/v9Y6WJAAAAAdDWjJqeN/CO1w2sh2Jutu/iB7BeP6ZcTNhAwZb+Dptu0cYs/5EsCNMBOljSQmOY1tMJ4hpM7JatzMXMu+xUcGQ== に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EncryptedGeminiApiKey {
            get {
                return ResourceManager.GetString("EncryptedGeminiApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAA5R+/frGFYUuoGX9oI3+FLgAAAAACAAAAAAAQZgAAAAEAACAAAAA+Cb7XuQ/wNB7P97oc5qE+drEGbFUosfnFBjXAAItLIwAAAAAOgAAAAAIAACAAAAB4WRibQ4KHglRbSh+ZnRNvBJMNSqj22NTX0Y9u6ZDFRLAAAABixAPBUBnXBdyleAEHlq4xiZjXa/H7mE/6SK3hZ1hKdu4kXVV22WJ/EIA0txfFK6KU3ZbuNkLiRQLxJ7c+/5Q387gboEWLLbttRMvKYnUXU4ZUwsw6BZnCDsFPSx4tJfhEBX2x8EzXwXhcZ6lyQFnlTfQ44m0tJhGGqeU1KfCFPYXuZf9m41jRTdmwlSVTwjkMFd6atL37mQocTzxIg/eozcrU1GlS+KfbTbuI5vPeoEAAAADnuqEtAO/AqZ7n3HT328H5BomMOPDdb6p5K1Rbl0uN3jQ++nGBPMNNLohue68c4zcq7p9k2igYjMzH [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EncryptedOpenAIApiKey {
            get {
                return ResourceManager.GetString("EncryptedOpenAIApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAA5R+/frGFYUuoGX9oI3+FLgAAAAACAAAAAAAQZgAAAAEAACAAAACWqAbRAo88dT7ehar74QvB2eTkXQ1oX/slWmpyOfdR7wAAAAAOgAAAAAIAACAAAAC62q8OdkorhNb+BgJAgoefYFq2xvi2B6ggpk3tR94S57AAAADORuB7JFb4v9fG7iBhO1dzSn1GlSu1zJ5QT4V5Ws2SXmWfs3gPsdkWV99+J5zyDcPSP1Hm/mYskTBFZvUUt550ldNAw0YsmzaSNke9f39yKPjD0DLkYmtvZ6pHg2L5RU3lVFUdvAysFU/u/nxP7/qRyYCgi169hEweL3+HvH5f1w9DoMZKrvacVMlB281in+xtD3nVptGuPS/Xz/cGebqa4N/xEJ0sTLC4WgQDuvqNu0AAAACFJ4oR3YYnO6SJKKRDZA6tUzNKW9gj6pzMgSZeW6jPraeAm56GVEIlKKZFkXlKjCRn9UVbJZTA9NG/ [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EncryptedVisionApiKey {
            get {
                return ResourceManager.GetString("EncryptedVisionApiKey", resourceCulture);
            }
        }
    }
}
