//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameTranslationOverlay.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameTranslationOverlay.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAAlmdUL4mMc0KNiQRrUAEWXAQAAAACAAAAAAAQZgAAAAEAACAAAAAkjRx/hs9vclBxYUnzPUWaWnmKxuyCOOQsQRZ3rXK1iwAAAAAOgAAAAAIAACAAAACuI1zQPASiWyiOyqLBV3W1yYQMS+IzlhOG+ABJj6nnuzAAAABPQr8cLfq76tv3P0NwZvj+/sDMaKOq58zKC8xU8cCWQamandbmI9yuP4vrsxyH3DNAAAAAI6no64yVDwoQSv7dqaOeg/rffjX4yyxJEU+JJceVi+y8ZuwuP8Ewl/IjmU1IL+lyhhY0iMpc8cucjq/PFwjT+w== に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EncryptedGeminiApiKey {
            get {
                return ResourceManager.GetString("EncryptedGeminiApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAAlmdUL4mMc0KNiQRrUAEWXAQAAAACAAAAAAAQZgAAAAEAACAAAABxzWkUbOCdW0JColWrOkmk97fKg1/jxBdJul6KbwdumwAAAAAOgAAAAAIAACAAAACe6q6y1B/eGQrU7/fvU4iQGh4XGLueDNPh72D+6iBKcLAAAACH/jUBpMTr8ZoB9fzE6bykrGlrZLLrRWn164+Jim40rAUCq1jvjlJG8p8LoolWSCuD9JZrUhNAfvXOqscrMHyosdit6Bx/pp05F5QYug6H7W2+LaIiatOj4tckGny1axu+dRRle/Sxd4x+gKhrsllTEe634FJGYY6mr4G3dR7fbE9b6LlcmAQZ4Iw9eevg8nO+n1/qKGyBEpXBNPdqBjkBRuA2oY+RwZRLg3yGYfus1EAAAACebHNP29kMwn63LmUjs7EpttMCFZhCZnooVWBtqiCnalqTZmRhAcSlJJTJCsyrSRIHLfvipx3xtstR [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EncryptedOpenAIApiKey {
            get {
                return ResourceManager.GetString("EncryptedOpenAIApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAAlmdUL4mMc0KNiQRrUAEWXAQAAAACAAAAAAAQZgAAAAEAACAAAABuWm+jJxrAMKmSMgITBR5PCIGTqVog02b6u9j/xES0GwAAAAAOgAAAAAIAACAAAADTiv1MqcfIWpMc5UcNd8pcizcbjcMRHbXrVC6A35JWA7AAAACiM82U1BcZIWVvZc47xRUayqxXp3iaS538wYONRbXhVLXFhwbvEvteZRfN7TQwDXwi/BA15cDiVlDNtli5PuB9iZUNrEuEKikAvZs8/Hh4b641t5vc0d0CcQNYngXLnEA3IpcD2Mxoqd9FGUDVvFem9bXVBAiNFohK79iwGPo1Ms0BBntavbaJwh/PJj+JpOeWX+HzxE1yCBwfaK8XTVVwVowwwbM1e497Z01H6oRVwkAAAACH0YpGBV1HAoDgY1KJCuKqS5u7TSas+yyAnaZPefKLLFCfsXBAVjGUX31z2EZ3QMdTrgJtABkMq+vk [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EncryptedVisionApiKey {
            get {
                return ResourceManager.GetString("EncryptedVisionApiKey", resourceCulture);
            }
        }
    }
}
